!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  enable_pose_offset: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      enable_pose_offset: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pose_offset: 1.5
      state: true
      type: ''
    state: []
  pose_offset: 1.5
state: []
